PlantillaMVC.Web/Models/AgregarCarta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlantillaMVC.Web.Models
{
    public class AgregarCarta
    {
        public int CartaId { get; set; } 
        public string Nombre { get; set; }

        public int Nivel { get; set; }
        //public string Tipo { get; set; }
        //public string Atributo { get; set; }
        //public string Descripcion { get; set; }
        //public string Categoria { get; set; }
        //public string Subcategoria { get; set; }
        //public int Ataque { get; set; }
        //public int Defensa { get; set; }
    }
}

PlantillaMVC.Web/Models/Carta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlantillaMVC.Web.Models
{
    public class Carta
    {
        public int CartaId { get; set; }
        public string Nombre { get; set; }
        public int Nivel { get; set; }
        public string Tipo { get; set; }
        public string Atributo { get; set; }
        public string Descripcion { get; set; }
        public string Categoria { get; set; }
        public string Subcategoria { get; set; }
        public int Ataque { get; set; }
        public int Defensa { get; set; }
        public string Exclusiva { get; set; }
    }
}

PlantillaMVC.Web/Models/ErrorViewModel.cs
using System;

namespace PlantillaMVC.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PlantillaMVC.Web/Models/Repositorio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlantillaMVC.Web.Models
{
    public class Repositorio
    {
        private static List<Carta> cartas = new List<Carta>();
        public static IEnumerable<Carta> Cartas => cartas;
        public static void AgregarCartaNueva(Carta carta) => cartas.Add(carta);
    
        public static IEnumerable<Carta> CartasRegistradas => cartas;


        public static Carta GetCarta(int id)
           => cartas.Find(c => c.CartaId == id);

        public static void EliminarCarta(Carta carta)
            => cartas.Remove(carta);

        public static void ActualizarCarta(Carta carta)
        {
            var indice = cartas.FindIndex(c => c.CartaId == carta.CartaId);
            if (indice != -1)
            {
                cartas[indice] = carta;
            }
        }
    }
}

PlantillaMVC.Web/Controllers/CartaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PlantillaMVC.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PlantillaMVC.Web.Controllers
{
    public class CartaController : Controller
    {
        public IActionResult Index()
        {
            return View(Repositorio.CartasRegistradas);
        }


        [HttpGet]
        public IActionResult FormAlta() => View();

        [HttpPost]
        public IActionResult FormAlta(Carta carta)
        {
            Repositorio.AgregarCartaNueva(carta);
            return View("Index", Repositorio.CartasRegistradas);
        }
        //public ViewResult ListaCartasRegistradas() => View(Repositorio.CartasRegistradas);

        [HttpGet]
        public IActionResult Eliminar() => View();

        [HttpPost]
        public IActionResult Eliminar(int id)
        {
            var cartaid = Repositorio.GetCarta(id);
            if (cartaid is null)
            {
                return NotFound();
            }
            Repositorio.EliminarCarta(cartaid);
            return View("Index", Repositorio.CartasRegistradas);
        }

        [HttpGet]
        public IActionResult Modificar(int id)
        {
            var cartaid = Repositorio.GetCarta(id);
            if (cartaid is null)
            {
                return NotFound();
            }
            return View(cartaid);
        }

        [HttpPost]
        public IActionResult Modificar(Carta carta)
        {
            Repositorio.ActualizarCarta(carta);
            return View("Index", Repositorio.CartasRegistradas);
        }

        [HttpGet]
        public IActionResult CaracteristicaCarta(int id)
        {
            var caract = Repositorio.GetCarta(id);
            
            return View(caract );

        }

        //[HttpGet]
        //public IActionResult CaracteristicaCarta(int id)
        //{
        //    var cartaId = Repositorio.GetCarta(id);
        //    if (cartaId is null)
        //    {
        //        return NotFound();
        //    }
        //    return View(cartaId);
        //}

        //public ViewResult CartaCaracteristica() => View(Repositorio.carac.caracteristicaLista);
    }

    
}

PlantillaMVC.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PlantillaMVC.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PlantillaMVC.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index() => View();

        [HttpGet]
        public IActionResult AgregarCartaForm() => View();



        //[HttpPost]
        //public IActionResult AgregarCartaForm(AgregarCarta agregarcarta)
        //{
        //    Repositorio.AgregarCartaNueva(agregarcarta);
        //    return View("Genial", agregarcarta);
        //}

        //[HttpPost]
        //public IActionResult Eliminar(AgregarCarta agregarcarta)
        //{
        //    //var carta = Repositorio.EliminarCarta(AgregarCarta agregarcarta);
        //    //if (carta is null)
        //    //{
        //    //    return NotFound();
        //    //}
        //    Repositorio.EliminarCarta(agregarcarta);
        //    return View("Genial", agregarcarta);
        //}

        //[HttpGet]
        //public IActionResult ModificarCarta()
        //{
        //    var carta = Repositorio.Where(c => c.Nomnre == unNombre);
        //    if (carta is null)
        //    {
        //        return NotFound();
        //    }
        //}

        //public ViewResult CartaCaracteristica() => View(Repositorio.caracteristicaLista);
        public ViewResult ListaCartasRegistradas() => View(Repositorio.CartasRegistradas);

        //private readonly ILogger<HomeController> _logger;

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        //public IActionResult Index()
        //{
        //    return View();
        //}

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}

        //public ViewResult Index() => View("PantallPrincipal");
    }
}

PlantillaMVC.Web/Views/Carta/CaracteristicaCarta.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@model IEnumerable<PlantillaMVC.Web.Models.Carta>*@
@model PlantillaMVC.Web.Models.Carta
@{ Layout = null; }
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous" />
<head>
    <title>Detalle @*@Model.Nombre*@ </title>
</head>
<body>
    @*<form asp-action="Modificar" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <label asp-for="CartaId">Id:</label>
            <input asp-for="CartaId" type="number" min="0" max="14000"/>
        </div>
        <div>
            <label asp-for="Nombre">Nombre:</label>
            <input asp-for="Nombre" type="text" />
        </div>
        <div>
            <label asp-for="Nivel">Nivel:</label>
            <input asp-for="Nivel" type="number" min="1" max="13" placeholder="Ingrese el nivel del monstruo" />
        </div>
        <div>
            <label asp-for="Atributo">Atributo:</label>
            <select asp-for="Atributo" required>
                <option value=""> </option>
                <option>Ninguna, es una Magica/Trampa</option>
                <option>Luz</option>
                <option>Oscurdad</option>
                <option>Fuego</option>
                <option>Viento</option>
                <option>Agua</option>
                <option>Tierra</option>
                <option>Divino</option>
            </select>
        </div>
        <div>
            <label>Categoria</label>
            <select asp-for="Categoria" required>
                <option value=""> </option>
                <option value="Monstruo">Monstruo</option>
                <option value="Trampa">Trampa</option>
                <option value="Magica">Magica</option>
            </select>
        </div>
        <div>
            <label>Subcategoria</label>
            <select asp-for="Subcategoria" required>
                <option value=""> </option>
                <option value="Normal">Normal</option>
                <option value="Efecto">Efecto</option>
                <option value="Toon">Toon</option>
                <option value="Tuner">Tuner</option>
                <option value="Gemini">Gemini</option>
                <option value="Fusion">Fusion</option>
                <option value="Sincronia">Sincronia</option>
                <option value="XYZ">XYZ</option>
                <option value="Pendulo">Pendulo</option>
                <option value="Link">Link</option>
                <option value="Ritual">Ritual</option>
                <option value="Spirit">Spirit</option>
                <option value="Continua">Continua</option>
                <option value="Juego Rapido">Juego Rapido</option>
                <option value="Equipo">Equipo</option>
                <option value="Campo">Campo</option>
                <option value="Contraefecto">Contraefecto</option>
            </select>
        </div>
        <div>
            <label asp-for="Tipo">Tipo:</label>
            <select asp-for="Tipo">
                <option value=""> </option>
                <option value="Ninguna es una Magica/Trampa">Ninguna es una Magica/Trampa</option>
                <option value="Hada">Hada</option>
                <option value="Demonio">Demonio</option>
                <option value="Guerrero">Guerrero</option>
                <option value="Guerrero-Bestias">Guerrero-Bestias</option>
                <option value="Reptil">Reptil</option>
                <option value="Piro">Piro</option>
                <option value="Aqua">Aqua</option>
                <option value="Pez">Pez</option>
                <option value="Lanzador de Conjurose">Lanzador de Conjuros</option>
                <option value="Dragon">Dragon</option>
                <option value="Ciberso">Ciberso</option>
                <option value="Maquina">Maquina</option>
                <option value="Bestia">Bestia</option>
                <option value="Roca">Roca</option>
                <option value="Bestia Alada">Bestia Alada</option>
                <option value="Trueno">Trueno</option>
                <option value="Wyrm">Wyrm</option>
                <option value="Serpiente Marina">Serpiente Marina</option>
                <option value="Psico">Psico</option>
                <option value="Dinosaurio">Dinosaurio</option>
                <option value="Insecto">Insecto</option>
                <option value="Cyborg">Cyborg</option>
                <option value="Magical Knight">Magical Knight</option>
                <option value="High Dragon">High Dragon</option>
                <option value="Omega Psychic">Omega Psychic</option>
                <option value="Celestial Warrior">Celestial Warrior</option>
                <option value="Galaxy">Galaxy</option>
                <option value="Bestia Divina">Bestia Divina</option>
                <option value="Dios Creador">Dios Creador</option>
            </select>
        </div>
        <div>
            <label asp-for="Ataque">Ataque:</label>
            <input asp-for="Ataque" type="number" min="0" max="10000" placeholder="Ingrese el ataque del monstruo" />
        </div>
        <div>
            <label asp-for="Defensa">Defensa:</label>
            <input asp-for="Defensa" type="number" min="0" max="10000" placeholder="Ingrese la defensa del monstruo" />
        </div>
        <div>
            <label asp-for="Descripcion">Descripcion:</label>
            <input asp-for="Descripcion" type="text" required|/>
        </div>*@

    @*<button type="submit">Modificar Carta</button>
        </form>*@

    <form asp-action="CaracteristicaCarta" method="post">
        <div class="container-fluid">


            <br />
            <table class="table table-bordered order-table">
                <thead>

                    <tr><th>Nombre</th><th>Id</th><th>Nivel</th><th>Atributo</th><th>Categoria</th><th>Subcategoria</th><th>Tipo</th><th>Ataque</th><th>Defensa</th><th>Descripcion</th><th>Exclusiva</th></tr>


                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        
                        
                            <tr>
                                @*<td>
                                    <a asp-controller="Carta" asp-action="FormAlta" asp-route-id="@carta.CartaId">@carta.Nombre</a>
                                </td>*@
                                <td>@Model.Nombre</td>
                                <td>@Model.CartaId</td>
                                <td>@Model.Nivel</td>
                                <td>@Model.Atributo</td>
                                <td>@Model.Categoria</td>
                                <td>@Model.Subcategoria</td>
                                <td>@Model.Tipo</td>
                                <td>@Model.Ataque</td>
                                <td>@Model.Defensa</td>
                                <td>@Model.Descripcion</td>
                                <td>@Model.Exclusiva</td>
                                <!--<td>-->
                                <!-- Formulario para el post-->
                                <!--</td>-->
                            </tr>
                        
                    }
                </tbody>
            </table>

            @*<button type="submit" class="btn btn-success">Volver al inicio</button>*@
            <a asp-controller="Carta" asp-action="Index" class="btn btn-success">Volver al Inicio</a>

        </div>
    </form>
</body>
</html>

PlantillaMVC.Web/Views/Carta/Eliminar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PlantillaMVC.Web.Models.Carta

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Carta eliminar</title>
</head>
<body>
    <form asp-action="Eliminar" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <label asp-for="CartaId">Id:</label>
            <input asp-for="CartaId" />
            <label asp-for="Nombre">Nombre:</label>
            <input asp-for="Nombre" />
        </div>
        <button type="submit">Eliminar carta</button>
    </form>
</body>
</html>

PlantillaMVC.Web/Views/Carta/FormAlta.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PlantillaMVC.Web.Models.Carta
@{ Layout = null; }

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<!DOCTYPE html>
<html>
<head>
    <title>Carta</title>
</head>
<body>
    <form asp-action="FormAlta" method="post">
        <div asp-validation-summary="All"></div>
        @*<div class="container-fluid">
            <label asp-for="CartaId">Id:</label>
            <input asp-for="CartaId" min="0" max="14000" required />
            <label asp-for="Nombre">Nombre:</label>
            <input asp-for="Nombre" required />
        </div>*@
        <div>
            <label asp-for="CartaId">Id:</label>
            <input asp-for="CartaId" type="number" min="0" max="14000" />
        </div>
        <div>
            <label asp-for="Nombre">Nombre:</label>
            <input asp-for="Nombre" type="text" />
        </div>
        <div>
            <label asp-for="Nivel">Nivel:</label>
            <input asp-for="Nivel" type="number" min="1" max="13" placeholder="Ingrese el nivel del monstruo" />
        </div>
        <div>
            <label asp-for="Atributo">Atributo:</label>
            <select asp-for="Atributo" required>
                <option value=""> </option>
                <option>Ninguna, es una Magica/Trampa</option>
                <option>Luz</option>
                <option>Oscurdad</option>
                <option>Fuego</option>
                <option>Viento</option>
                <option>Agua</option>
                <option>Tierra</option>
                <option>Divino</option>
            </select>
        </div>
        <div>
            <label>Categoria</label>
            <select asp-for="Categoria" required>
                <option value=""> </option>
                <option value="Monstruo">Monstruo</option>
                <option value="Trampa">Trampa</option>
                <option value="Magica">Magica</option>
            </select>
        </div>
        <div>
            <label>Subcategoria</label>
            <select asp-for="Subcategoria" required>
                <option value=""> </option>
                <option value="Normal">Normal</option>
                <option value="Efecto">Efecto</option>
                <option value="Toon">Toon</option>
                <option value="Tuner">Tuner</option>
                <option value="Gemini">Gemini</option>
                <option value="Fusion">Fusion</option>
                <option value="Sincronia">Sincronia</option>
                <option value="XYZ">XYZ</option>
                <option value="Pendulo">Pendulo</option>
                <option value="Link">Link</option>
                <option value="Ritual">Ritual</option>
                <option value="Spirit">Spirit</option>
                <option value="Continua">Continua</option>
                <option value="Juego Rapido">Juego Rapido</option>
                <option value="Equipo">Equipo</option>
                <option value="Campo">Campo</option>
                <option value="Contraefecto">Contraefecto</option>
            </select>
        </div>
        <div>
            <label asp-for="Tipo">Tipo:</label>
            <select asp-for="Tipo">
                <option value=""> </option>
                <option value="Ninguna es una Magica/Trampa">Ninguna es una Magica/Trampa</option>
                <option value="Hada">Hada</option>
                <option value="Demonio">Demonio</option>
                <option value="Guerrero">Guerrero</option>
                <option value="Guerrero-Bestias">Guerrero-Bestias</option>
                <option value="Reptil">Reptil</option>
                <option value="Piro">Piro</option>
                <option value="Aqua">Aqua</option>
                <option value="Pez">Pez</option>
                <option value="Lanzador de Conjurose">Lanzador de Conjuros</option>
                <option value="Dragon">Dragon</option>
                <option value="Ciberso">Ciberso</option>
                <option value="Maquina">Maquina</option>
                <option value="Bestia">Bestia</option>
                <option value="Roca">Roca</option>
                <option value="Bestia Alada">Bestia Alada</option>
                <option value="Trueno">Trueno</option>
                <option value="Wyrm">Wyrm</option>
                <option value="Serpiente Marina">Serpiente Marina</option>
                <option value="Psico">Psico</option>
                <option value="Dinosaurio">Dinosaurio</option>
                <option value="Insecto">Insecto</option>
                <option value="Cyborg">Cyborg</option>
                <option value="Magical Knight">Magical Knight</option>
                <option value="High Dragon">High Dragon</option>
                <option value="Omega Psychic">Omega Psychic</option>
                <option value="Celestial Warrior">Celestial Warrior</option>
                <option value="Galaxy">Galaxy</option>
                <option value="Bestia Divina">Bestia Divina</option>
                <option value="Dios Creador">Dios Creador</option>
            </select>
        </div>
        <div>
            <label asp-for="Ataque">Ataque:</label>
            <input asp-for="Ataque" type="number" min="0" max="10000" placeholder="Ingrese el ataque del monstruo" />
        </div>
        <div>
            <label asp-for="Defensa">Defensa:</label>
            <input asp-for="Defensa" type="number" min="0" max="10000" placeholder="Ingrese la defensa del monstruo" />
        </div>
        <div>
            <label asp-for="Descripcion">Descripcion:</label>
            <input asp-for="Descripcion" type="text" required />
        </div>
        <div>
            <label>Exclusiva</label>
            <select asp-for="Exclusiva" required>
                <option value=""> </option>
                <option value="TCG (Occidente)">TCG (Occidente)</option>
                <option value="OCG (Oriente)">OCG (Oriente)</option>
                <option value="TCG USA">TCG USA</option>
                <option value="Anime">Anime</option>
                <option value="TCG/OCG">TCG/OCG</option>
                <option value="Rush Duel">Rush Duel</option>
            </select>
        </div>
        <button class="btn btn-primary" type="submit">Alta Carta</button>
    </form>
</body>
</html>

PlantillaMVC.Web/Views/Carta/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<PlantillaMVC.Web.Models.Carta>
@{
    Layout = null; }

     <script type="text/javascript">
				(function(document) {
      'use strict';

      var filtrarTabla = (function(Arreglo) {

        var input;

        function entradaEvento(nombre) {
          input = nombre.target;
          var tablas = document.getElementsByClassName(input.getAttribute('data-table'));
          Arreglo.forEach.call(tablas, function(table) {
            Arreglo.forEach.call(table.tBodies, function(tbody) {
              Arreglo.forEach.call(tbody.rows, _filter);
            });
          });
        }

        function _filter(row) {
          var texto = row.textContent.toLowerCase(), val = input.value.toLowerCase();
          row.style.display = texto.indexOf(val) === -1 ? 'none' : 'table-row';
        }

        return {
          init: function() {
            var inputs = document.getElementsByClassName('light-table-filter');
            Arreglo.forEach.call(inputs, function(Input) {
              Input.oninput = entradaEvento;
            });
          }
        };
      })(Array.prototype);

      document.addEventListener('readystatechange', function() {
        if (document.readyState === 'complete') {
          filtrarTabla.init();
        }
      });

    })(document);

			</script>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


<!DOCTYPE html>
<html>
<head>
    <title>Cartas</title>
</head>
<body>
    <a asp-action="FormAlta" class="btn btn-success">Alta Carta</a><br />
    <h5>Cartas</h5>

    <div class="container-fluid">
        <input class="form-control col-md-3 light-table-filter" data-table="order-table" type="text" placeholder="Ingrese el nombre de la carta">
        <br />
    <table class="table table-bordered order-table">
        <thead>

            <tr><th>Nombre</th><th>Nivel</th><th>Descripcion</th></tr>


        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach (PlantillaMVC.Web.Models.Carta carta in Model)
                {
                    <tr>
                        <td>
                            <a  asp-controller="Carta" asp-action="CaracteristicaCarta" asp-route-id="@carta.CartaId">@carta.Nombre</a>
                        </td>
                        <td>@carta.Nivel</td>
                        
                        <td>@carta.Descripcion</td>
                        <td>

                            <!-- Formulario para el post-->
                            <form asp-controller="Carta" asp-action="Eliminar" method="post">
                                <input type="hidden" asp-for="@carta.CartaId" />
                                <button type="submit" asp-controller="Carta" asp-action="Eliminar" asp-route-id="@carta.CartaId">Eliminar</button>
                                <a asp-controller="Carta" asp-action="Modificar" asp-route-id="@carta.CartaId">Modificar</a>
                            </form>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    </div>
</body>
</html>

PlantillaMVC.Web/Views/Home/AgregarCartaForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model PlantillaMVC.Web.Models.AgregarCarta
@{ 
    Layout = null; 
}
<!DOCTYPE html>
<html>
<head>
    <title>Formulario Agregar Carta</title>
</head>
<body>
    <form asp-action="AgregarCartaForm" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <label asp-for="Nombre">Nombre:</label>
            <input asp-for="Nombre" />
        </div>
        <button type="submit">Enviar respuesta</button>
    </form>
</body>
</html>

PlantillaMVC.Web/Views/Home/Genial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model PlantillaMVC.Web.Models.AgregarCarta
@{ Layout = null; }
<!DOCTYPE html>
<html>
<head>
    <title>Gracias por registrar una carta</title>
</head>
<body>
    <div>
        <h1>¡Gracias, Carta @Model.Nombre !</h1>
    </div>
    Click <a asp-action="ListaCartasRegistradas">aca</a> para ver quienes vienen.
</body>
</html>

PlantillaMVC.Web/Views/Home/Index.cshtml
@*@{ ViewData["Title"] = "Homeeeee Page"; }

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Ahhh Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p> Hace clic <a asp-action="AgregarCartaForm">aca</a> </p>
</div>*@

@model PlantillaMVC.Web.Models.AgregarCarta
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    <a asp-controller="Carta" asp-action="Index" class="btn btn-success">Cartas</a>
</body>
</html>

PlantillaMVC.Web/Views/Home/ListaCartasRegistradas.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<PlantillaMVC.Web.Models.AgregarCarta>
@{ Layout = null; }
<!DOCTYPE html>
<html>
<head>
    <title>Respuestas</title>
</head>
<body>
    <h2>Cartas Registradas</h2>
    <table>
        <thead>
            <tr><th>Nombre</th></tr>
        </thead>
        <tbody>
            @foreach (PlantillaMVC.Web.Models.AgregarCarta agregarCarta in Model)
            {
<tr>
    <td>
        @agregarCarta.Nombre
        <form asp-action="Eliminar" method="post">
  
            <input type="hidden" asp-for="@agregarCarta.Nombre" />
            <button type="submit">Eliminar</button>
            <a asp-action="ModificarCarta" asp-route-id="@agregarCarta.Nombre">Modificar</a>

        </form>
    </td>
</tr>            }
        </tbody>
    </table>
    <hr />
    <a asp-action="AgregarCartaForm">Ingresar otra respuesta</a><br />
    <a asp-action="Index">Volver al Inicio</a>
</body>
</html>

PlantillaMVC.Web/Views/Home/ModificarCarta.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PlantillaMVC.Web.Models.AgregarCarta
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Formulario Agregar Carta</title>
</head>
<body>
    <form asp-action="ModificarCarta" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <label asp-for="@Model.Nombre">Nombre:</label>
            <input asp-for="@Model.Nombre" required />
        </div>
        <button type="submit">Modificar Carta</button>
    </form>
</body>
</html>

PlantillaMVC.Web/Views/Home/PantallaPrincipal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}

<html>
    <head>
        <title> "Pantalla Principal" </title>
    </head>
    <body>
        <h1>Hola Mundo</h1>
    </body>
</html>